<a href="https://colab.research.google.com/github/kaixiang164-byte/ML-Intern-Notebook/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## list
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]


In [ ]:
## function
def square(x):
  return x*x

square(5)

25

In [ ]:
## practice 1: find mean( version 1& 2 )
def mean_1(numbers):
  total = 0
  for x in numbers:
    total = total + x
  return total/ len(numbers)

mean_1(numbers)

def mean_2(numbers):
  total = 0
  count = 0
  for x in numbers:
    total= total + x
    count = count + 1
  return total/count

mean_2(numbers)

3.0

In [ ]:
## practice 2: square_mean
def smean(numbers):
  total = 0
  count = 0

  for x in numbers:
    total = total + x*x
    count = count + 1
  return total/count

smean([1,3])


5.0

In [ ]:
## practice 3: variance
def variance(numbers):
  total = 0
  mu = mean_1(numbers)

  for x in numbers:
    total = total + (x - mu)**2

  return total/len(numbers)

variance([1,3])

1.0

In [ ]:
## practice 4: standardization
import numpy as np

def standardize(numbers):

  mu = mean_1(numbers)
  sigma = (variance(numbers))**0.5
  standardization_list = []

  for x in numbers:
    standardization_list.append((x - mu)/sigma)

  return standardization_list

standardize([1,3])



[-1.0, 1.0]

In [ ]:
## numpy
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
type(a)


[1 2 3 4 5]


numpy.ndarray

In [ ]:
# differnce between numpy and python basics
python_list = [1,2,3]

python_list*2

[1, 2, 3, 1, 2, 3]

In [ ]:
numpy_array = np.array([1,2,3])

numpy_array*2

array([2, 4, 6])

In [ ]:
np.mean(a)

np.float64(3.0)

In [ ]:
a.mean()

np.float64(3.0)

In [ ]:
## Matrix
X = np.array([
    [1,2],
    [3,4],
    [5,6]
])
X.shape

(3, 2)

In [ ]:
## indexing
import numpy as np

X = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

X.shape

X[0,0]

X[1,2]

X[2]

X[:, 0]

X[:, 1]

X[:2, :]

X[:, :2]


array([[10, 20],
       [40, 50],
       [70, 80]])

In [ ]:
## matrix multiplication
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5],
    [6]
])

A@B

array([[17],
       [39]])

In [ ]:
## LINEAR REGRESSION
X = np.array([
    [5,8],
    [10,6],
    [3,9]
])

w = np.array([
    [2],
    [1]
])

y_pred = X @ w

In [ ]:
X.shape

w.shape

y_pred.shape

(3, 1)

In [ ]:
## practice
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

# first 3 rows
X[:3,:]

# row 2 and 3
X[1:3,:]

# last row
X[-1:,:]

array([[10, 11, 12]])

In [ ]:
range(8)

range(0, 8)

In [ ]:
## leetcode two sum double loop
def two_sum_double_loop(nums,target):
  search_list = []

  for i in range(len(nums)):
    for j in range(i+1,len(nums)):
      if nums[i] + nums [j] == target:
        search_list.append(i)
        search_list.append(j)
        return search_list

  return search_list



two_sum_double_loop(nums=[2,7,11,15],target=17)



[0, 3]

In [ ]:
seen = {}

seen[2] = 0
seen[7] = 1

print(seen)

if 2 in seen:
    print("found")

In [ ]:
## leetcode two sum dict

def two_sum_dict_loop(nums, target):
  seen = {}

  for pos,x in enumerate(nums):
    print(pos,x)
    print("current: ", x)
    print("need: ", target - x)
    print("seen: ", seen)

    if (target - x) in seen:
      return [seen[target - x], pos]

    seen[x] = pos

  return []

two_sum_dict_loop(nums = [2,7,11,2,15],target = 4)


0 2
current:  2
need:  2
seen:  {}
1 7
current:  7
need:  -3
seen:  {2: 0}
2 11
current:  11
need:  -7
seen:  {2: 0, 7: 1}
3 2
current:  2
need:  2
seen:  {2: 0, 7: 1, 11: 2}


[0, 3]

In [ ]:
## counting frequency
words = ["apple","banana","apple","orange","banana","apple"]

def counting_fruits(words):
  fruit_dict = {}
  apple = 0
  banana = 0
  orange = 0
  for word in words:
    if word == "apple":
      apple = apple + 1
      fruit_dict[word] = apple
    elif word =="banana":
      banana = banana + 1
      fruit_dict[word] = banana
    else:
      orange = orange + 1
      fruit_dict[word] = orange
  return fruit_dict

counting_fruits(words)

{'apple': 3, 'banana': 2, 'orange': 1}

In [4]:
## counting frequency correct version
def counting_frequency(words):
  words_dict = {}
  for word in words:
    if word in words_dict:
      words_dict[word] += 1
    else:
      words_dict[word] = 1
  return words_dict

counting_frequency(["apple","banana","apple","orange","banana","apple"])

{'apple': 3, 'banana': 2, 'orange': 1}